name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.0
      with:
        java-version: 11

    - name: Build Gatsby app
      run: ./gradlew :gatsby-app:build

    - name: Build Spring app
      run: ./gradlew bootjar
      
    - name: Test
      run: ./gradlew --continue test
      
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: '**/build/test-results/test/TEST-*.xml'

    - name: Generate documentation
      run: ./gradlew asciidoctor
