name: ESLint
on:
  push:
  pull_request:

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install
        run: cd ./next-app && yarn install
      - name: Run ESLint
        run: cd ./next-app && npx eslint @types src